@extends('layouts.app')

@section('title', 'Home | Sitolu Huta')
@section('content')
<h1 class="mb-2 text-3xl font-bold tracking-tight text-gray-900 dark:text-white">Profil Desa</h1>
<p class="font-normal text-gray-700 dark:text-gray-400 mb-2">
    Desa Sitoluhuta, yang terletak di Kabupaten Samosir, Sumatera Utara, merupakan sebuah permata tersembunyi yang menawarkan keindahan alam yang menakjubkan dan kekayaan budaya yang tak ternilai. Desa ini memiliki luas daratan yang cukup kompak, yaitu sebesar 2,3 kilometer persegi atau setara dengan 230 hektar. Topografi Desa Sitoluhuta terbagi menjadi dua bagian utama: 60% dari wilayahnya merupakan dataran rendah yang subur, sementara 40% sisanya terdiri dari perbukitan yang mempesona.
    Keunikan Desa Sitoluhuta terletak pada perpaduan harmonis antara berbagai elemen lanskapnya. Di sini, pengunjung dapat menyaksikan panorama perbukitan yang hijau dan menenangkan, lahan pertanian yang produktif dan terpelihara dengan baik, serta keindahan danau air tawar yang jernih dan menyegarkan. Semua ini dibalut dengan kearifan budaya lokal yang telah diwariskan secara turun-temurun, menciptakan suasana yang autentik dan memikat.
    Potensi Desa Sitoluhuta tidak hanya terbatas pada keindahan alamnya saja. Desa ini telah mengembangkan dua sektor utama yang menjadi tulang punggung perekonomian masyarakat setempat. Pertama, sektor pertanian yang memanfaatkan kesuburan tanah dan iklim yang mendukung untuk menghasilkan berbagai jenis tanaman pangan dan komoditas pertanian lainnya. Kedua, sektor pariwisata yang memanfaatkan keindahan alam dan kekayaan budaya desa untuk menarik wisatawan, baik domestik maupun mancanegara.
    Selain dua sektor utama tersebut, Desa Sitoluhuta juga menunjukkan perkembangan yang menggembirakan dalam bidang ekonomi kreatif. Salah satu contoh yang paling menonjol adalah kerajinan tenun kain ulos, sebuah warisan budaya yang telah diadaptasi dan dikembangkan oleh para pengrajin lokal. Kain ulos, dengan motif dan warnanya yang khas, tidak hanya menjadi simbol identitas budaya, tetapi juga menjadi sumber penghasilan tambahan bagi masyarakat desa.
    Para pengrajin tenun kain ulos di Desa Sitoluhuta tidak hanya melestarikan teknik pembuatan tradisional, tetapi juga terus berinovasi untuk menghasilkan produk-produk yang sesuai dengan selera pasar modern. Hal ini menunjukkan bagaimana masyarakat desa mampu memadukan kearifan lokal dengan tuntutan zaman, menciptakan peluang ekonomi baru tanpa meninggalkan akar budaya mereka.
    Dengan kombinasi antara keindahan alam, kekayaan budaya, dan potensi ekonomi yang beragam, Desa Sitoluhuta menawarkan contoh yang inspiratif tentang bagaimana sebuah desa dapat berkembang secara berkelanjutan. Melalui pengelolaan sumber daya alam yang bijaksana, pelestarian warisan budaya, dan pengembangan sektor-sektor ekonomi yang relevan, Desa Sitoluhuta tidak hanya mampu meningkatkan kesejahteraan masyarakatnya, tetapi juga menjaga kelestarian lingkungan dan memperkuat identitas kulturalnya.
</p>
<h1 class="my-3 text-3xl font-bold tracking-tight text-gray-900 dark:text-white">Video Profil</h1>
<h1 class="my-3 text-3xl font-bold tracking-tight text-gray-900 dark:text-white">Foto</h1>
@endsection